package org.clarkecollective.raderie

import org.clarkecollective.raderie.models.HumanValue

class ValueRepo {

    fun freshDeck(): List<HumanValue> {
        return humanValueList.mapIndexed { index, s ->
                HumanValue(index, s, 0, 0, 0, 0, 0, 0.00)
        }
    }

    fun freshDeckObject() = hvObjectList

    private val humanValueList = arrayOf(
        "Acceptance",
        "Accomplishment",
        "Accountability",
        "Accuracy",
        "Achievement",
        "Adaptability",
        "Alertness",
        "Altruism",
        "Ambition",
        "Amusement",
        "Assertiveness",
        "Attentiveness",
        "Awareness",
        "Balance",
        "Beauty",
        "Boldness",
        "Bravery",
        "Brilliance",
        "Calm",
        "Candor",
        "Capability",
        "Careful",
        "Certainty",
        "Challenge",
        "Charity",
        "Cleanliness",
        "Clarity",
        "Clever",
        "Comfort",
        "Commitment",
        "Common sense",
        "Communication",
        "Community",
        "Compassion",
        "Competence",
        "Concentration",
        "Confidence",
        "Connection",
        "Consciousness",
        "Consistency",
        "Contentment",
        "Contribution",
        "Control",
        "Conviction",
        "Cooperation",
        "Courage",
        "Courtesy",
        "Creativity",
        "Credibility",
        "Curiosity",
        "Decisiveness",
        "Dedication",
        "Dependability",
        "Determination",
        "Development",
        "Devotion",
        "Dignity",
        "Discipline",
        "Discovery",
        "Dreams",
        "Drive",
        "Duty",
        "Earnestness",
        "Effectiveness",
        "Efficiency",
        "Elegance",
        "Empathy",
        "Endurance",
        "Energy",
        "Enjoyment",
        "Enthusiasm",
        "Equity",
        "Ethics",
        "Excellence",
        "Excitement",
        "Experience",
        "Exercise",
        "Exploration",
        "Expressiveness",
        "Faith",
        "Fairness",
        "Family",
        "Fame",
        "Favors",
        "Fearlessness",
        "Feelings",
        "Ferocity",
        "Fidelity",
        "Flexibility",
        "Focus",
        "Foresight",
        "Forgiveness",
        "Fortitude",
        "Freedom",
        "Friendship",
        "Fun",
        "Generosity",
        "Genius",
        "Giving",
        "Goodness",
        "Grace",
        "Gratitude",
        "Greatness",
        "Growth",
        "Guidance",
        "Happiness",
        "Hard work",
        "Harmony",
        "Health",
        "Helping Friends",
        "Helping Strangers",
        "Honesty",
        "Honor",
        "Hope",
        "Hospitality",
        "Humility",
        "Imagination",
        "Improvement",
        "Independence",
        "Individuality",
        "Industriousness",
        "Influence",
        "Innovation",
        "Inquisitiveness",
        "Insight",
        "Inspiration",
        "Integrity",
        "Intelligence",
        "Intensity",
        "Intimacy",
        "Intuition",
        "Inventiveness",
        "Irreverence",
        "Joy",
        "Justice",
        "Kindness",
        "Knowledge",
        "Lawful",
        "Leadership",
        "Learning",
        "Liberty",
        "Logic",
        "Love",
        "Loyalty",
        "Mastery",
        "Maturity",
        "Meaning",
        "Moderation",
        "Motivation",
        "Openness",
        "Optimism",
        "Order",
        "Organization",
        "Originality",
        "Passion",
        "Patience",
        "Peace",
        "Performance",
        "Persistence",
        "Playfulness",
        "Poise",
        "Potential",
        "Power",
        "Presence",
        "Productivity",
        "Professionalism",
        "Prosperity",
        "Punctuality",
        "Purpose",
        "Rationality",
        "Realism",
        "Reason",
        "Recognition",
        "Recreation",
        "Refinement",
        "Reflection",
        "Reliability",
        "Resilience",
        "Resolution",
        "Respect",
        "Responsibility",
        "Responsiveness",
        "Rest",
        "Restraint",
        "Results-oriented",
        "Reverence",
        "Rigor",
        "Risk-Taking",
        "Satisfaction",
        "Security",
        "Self-reliance",
        "Self-awareness",
        "Self-control",
        "Selflessness",
        "Sensitivity",
        "Serenity",
        "Service",
        "Sharing",
        "Silence",
        "Simplicity",
        "Sincerity",
        "Skillfulness",
        "Solitude",
        "Spirituality",
        "Spontaneity",
        "Stability",
        "Status",
        "Stewardship",
        "Strength",
        "Structure",
        "Success",
        "Support",
        "Surprise",
        "Sustainability",
        "Sympathy",
        "Talent",
        "Teamwork",
        "Temperance",
        "Thankfulness",
        "Thoroughness",
        "Thoughtfulness",
        "Timeliness",
        "Tolerance",
        "Toughness",
        "Tradition",
        "Tranquility",
        "Transparency",
        "Trust",
        "Trustworthy",
        "Truth",
        "Understanding",
        "Uniqueness",
        "Unity",
        "Valor",
        "Victory",
        "Vigor",
        "Vision",
        "Vitality",
        "Wealth",
        "Welcoming",
        "Wholeness",
        "Wisdom",
        "Wonder",
        "Worthiness",
        "Zeal"
    )

    val hvObjectList = arrayListOf(
        HumanValue(0, "Acceptance"),
        HumanValue(1, "Accomplishment"),
        HumanValue(2, "Accountability"),
        HumanValue(3, "Accuracy"),
        HumanValue(4, "Achievement"),
        HumanValue(5, "Adaptability"),
        HumanValue(6, "Alertness"),
        HumanValue(7, "Altruism"),
        HumanValue(8, "Ambition"),
        HumanValue(9, "Amusement"),
        HumanValue(10, "Assertiveness"),
        HumanValue(11, "Attentiveness"),
        HumanValue(12, "Awareness"),
        HumanValue(13, "Balance"),
        HumanValue(14, "Beauty"),
        HumanValue(15, "Boldness"),
        HumanValue(16, "Bravery"),
        HumanValue(17, "Brilliance"),
        HumanValue(18, "Calm"),
        HumanValue(19, "Candor"),
        HumanValue(20, "Capability"),
        HumanValue(21, "Carefulness"),
        HumanValue(22, "Certainty"),
        HumanValue(23, "Challenge"),
        HumanValue(24, "Charisma"),
        HumanValue(25, "Charity"),
        HumanValue(26, "Cheerfulness"),
        HumanValue(27, "Clarity"),
        HumanValue(28, "Cleanliness"),
        HumanValue(29, "Clear-headedness"),
        HumanValue(30, "Cleverness"),
        HumanValue(31, "Comfort"),
        HumanValue(32, "Commitment"),
        HumanValue(33, "Communication"),
        HumanValue(34, "Community"),
        HumanValue(35, "Compassion"),
        HumanValue(36, "Competence"),
        HumanValue(37, "Composure"),
        HumanValue(38, "Concentration"),
        HumanValue(39, "Confidence"),
        HumanValue(40, "Conformity"),
        HumanValue(41, "Conscientiousness"),
        HumanValue(42, "Connection"),
        HumanValue(43, "Consciousness"),
        HumanValue(44, "Consideration"),
        HumanValue(45, "Consistency"),
        HumanValue(46, "Contentment"),
        HumanValue(47, "Contribution"),
        HumanValue(48, "Control"),
        HumanValue(49, "Conviction"),
        HumanValue(50, "Cooperation"),
        HumanValue(51, "Courage"),
        HumanValue(52, "Courtesy"),
        HumanValue(53, "Creativity"),
        HumanValue(54, "Credibility"),
        HumanValue(55, "Curiosity"),
        HumanValue(56, "Decisiveness"),
        HumanValue(57, "Decorum"),
        HumanValue(58, "Dedication"),
        HumanValue(59, "Dependability"),
        HumanValue(60, "Determination"),
        HumanValue(61, "Development"),
        HumanValue(62, "Devotion"),
        HumanValue(63, "Dignity"),
        HumanValue(64, "Discipline"),
        HumanValue(65, "Discovery"),
         HumanValue(66, "dreams"),
        HumanValue(67, "drive"),
     HumanValue(68, "duty"),
     HumanValue(69, "earnestness"),
     HumanValue(70, "effectiveness"),
     HumanValue(71, "efficiency"),
     HumanValue(72, "elegance"),
     HumanValue(73, "empathy"),
     HumanValue(74, "endurance"),
     HumanValue(75, "energy"),
     HumanValue(76, "enjoyment"),
     HumanValue(77, "enthusiasm"),
     HumanValue(78, "equity"),
     HumanValue(79, "ethics"),
     HumanValue(80, "excellence"),
     HumanValue(81, "excitement"),
     HumanValue(82, "experience"),
     HumanValue(83, "exercise"),
     HumanValue(84, "exploration"),
     HumanValue(85, "expressiveness"),
     HumanValue(86, "faith"),
     HumanValue(87, "fairness"),
     HumanValue(88, "fame"),
     HumanValue(89, "favors"),
     HumanValue(90, "fearlessness"),
     HumanValue(91, "feelings"),
     HumanValue(92, "ferocity"),
     HumanValue(93, "fidelity"),
     HumanValue(94, "flexibility"),
     HumanValue(95, "focus"),
     HumanValue(96, "foresight"),
     HumanValue(97, "forgiveness"),
     HumanValue(98, "fortitude"),
     HumanValue(99, "freedom"),
     HumanValue(100, "friendship"),
     HumanValue(101, "generosity"),
     HumanValue(102, "genius"),
     HumanValue(103, "giving"),
     HumanValue(104, "goodness"),
     HumanValue(105, "grace"),
     HumanValue(106, "gratitude"),
     HumanValue(107, "greatness"),
     HumanValue(108, "growth"),
     HumanValue(109, "guidance"),
     HumanValue(110, "happiness"),
     HumanValue(111, "hard_work"),
     HumanValue(112, "harmony"),
     HumanValue(113, "health"),
     HumanValue(114, "helping_friends"),
     HumanValue(115, "helping_strangers"),
     HumanValue(116, "honesty"),
     HumanValue(117, "honor"),
     HumanValue(118, "hope"),
     HumanValue(119, "hospitality"),
     HumanValue(120, "humility"),
     HumanValue(121, "imagination"),
     HumanValue(122, "improvement"),
     HumanValue(123, "independence"),
     HumanValue(124, "individuality"),
     HumanValue(125, "industriousness"),
     HumanValue(126, "influence"),
     HumanValue(127, "innovation"),
     HumanValue(128, "inquisitiveness"),
     HumanValue(129, "insight"),
     HumanValue(130, "inspiration"),
     HumanValue(131, "integrity"),
     HumanValue(132, "intelligence"),
     HumanValue(133, "intensity"),
     HumanValue(134, "intimacy"),
     HumanValue(135, "intuition"),
     HumanValue(136, "inventiveness"),
     HumanValue(137, "joy"),
     HumanValue(138, "justice"),
     HumanValue(139, "kindness"),
     HumanValue(140, "knowledge"),
     HumanValue(141, "lawfulness"),
     HumanValue(142, "leadership"),
     HumanValue(143, "learning"),
     HumanValue(144, "liberty"),
     HumanValue(145, "logic"),
     HumanValue(146, "love"),
     HumanValue(147, "loyalty"),
     HumanValue(148, "mastery"),
     HumanValue(149, "maturity"),
     HumanValue(150, "meaning"),
     HumanValue(151, "moderation"),
     HumanValue(152, "motivation"),
     HumanValue(153, "openness"),
     HumanValue(154, "optimism"),
     HumanValue(155, "order"),
     HumanValue(156, "organization"),
     HumanValue(157, "originality"),
     HumanValue(158, "passion"),
     HumanValue(159, "patience"),
     HumanValue(160, "peace"),
     HumanValue(161, "performance"),
     HumanValue(162, "persistence"),
     HumanValue(163, "playfulness"),
     HumanValue(164, "poise"),
     HumanValue(165, "potential"),
     HumanValue(166, "power"),
     HumanValue(167, "presence"),
     HumanValue(168, "productivity"),
     HumanValue(169, "professionalism"),
     HumanValue(170, "prosperity"),
     HumanValue(171, "punctuality"),
     HumanValue(172, "purpose"),
     HumanValue(173, "rationality"),
     HumanValue(174, "realism"),
     HumanValue(175, "reason"),
     HumanValue(176, "recognition"),
     HumanValue(177, "recreation"),
     HumanValue(178, "refinement"),
     HumanValue(179, "reflection"),
     HumanValue(180, "reliability"),
     HumanValue(181, "resilience"),
     HumanValue(182, "resolution"),
     HumanValue(183, "resourcefulness"),
     HumanValue(184, "respect"),
     HumanValue(185, "responsibility"),
     HumanValue(186, "responsiveness"),
     HumanValue(187, "rest"),
     HumanValue(188, "restraint"),
     HumanValue(189, "reverence"),
     HumanValue(190, "rigor"),
     HumanValue(191, "risk_taking"),
     HumanValue(192, "satisfaction"),
     HumanValue(193, "security"),
     HumanValue(194, "self_reliance"),
     HumanValue(195, "self_awareness"),
     HumanValue(196, "self_control"),
     HumanValue(197, "selflessness"),
     HumanValue(198, "sensitivity"),
     HumanValue(199, "serenity"),
     HumanValue(200, "service"),
     HumanValue(201, "sharing"),
     HumanValue(202, "silence"),
     HumanValue(203, "simplicity"),
     HumanValue(204, "sincerity"),
     HumanValue(205, "skillfulness"),
     HumanValue(206, "solitude"),
     HumanValue(207, "spirituality"),
     HumanValue(208, "spontaneity"),
     HumanValue(209, "stability"),
     HumanValue(210, "status"),
     HumanValue(211, "stewardship"),
     HumanValue(212, "strength"),
     HumanValue(213, "structure"),
     HumanValue(214, "success"),
     HumanValue(215, "support"),
     HumanValue(216, "surprise"),
     HumanValue(217, "sustainability"),
     HumanValue(218, "sympathy"),
     HumanValue(219, "talent"),
     HumanValue(220, "teamwork"),
     HumanValue(221, "temperance"),
     HumanValue(222, "thankfulness"),
     HumanValue(223, "thoroughness"),
     HumanValue(224, "thoughtfulness"),
     HumanValue(225, "thrift"),
     HumanValue(226, "timelessness"),
     HumanValue(227, "tolerance"),
     HumanValue(228, "toughness"),
     HumanValue(229, "tradition"),
     HumanValue(230, "tranquility"),
     HumanValue(231, "transparency"),
     HumanValue(232, "trust"),
     HumanValue(233, "trustworthiness"),
     HumanValue(234, "truth"),
     HumanValue(235, "understanding"),
     HumanValue(236, "uniqueness"),
     HumanValue(237, "unity"),
     HumanValue(238, "valor"),
     HumanValue(239, "victory"),
     HumanValue(240, "vigor"),
     HumanValue(241, "vision"),
     HumanValue(242, "vitality"),
     HumanValue(243, "wealth"),
     HumanValue(244, "welcoming"),
     HumanValue(245, "wholeness"),
     HumanValue(246, "wisdom"),
     HumanValue(247, "wonder"),
     HumanValue(248, "worthiness"),
     HumanValue(249, "zeal"),

    )
}